<?php
/** Site footer. */
?>
<footer>
	<div class="footer-grid">
		<div class="footer-intro"><a class="footer-logo" href="<?php echo esc_url( home_url( '/' ) ); ?>" aria-label="Rebekah's home"><img src="<?php echo esc_url( rhn_theme_asset( 'tmp/source/current-site-logo-live.png' ) ); ?>" alt="Rebekah's Health & Nutrition Source"></a><p>Trusted products. Practical education. Guidance that feels personal.</p><div class="footer-connect" id="footer-connect" aria-label="Social media links"><div class="social-icons"><a class="social-icon" href="https://www.instagram.com/rebekahs_health_and_nutrition/" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.9"><rect x="3" y="3" width="18" height="18" rx="5"></rect><circle cx="12" cy="12" r="4.1"></circle><circle cx="17.4" cy="6.7" r="1" fill="currentColor" stroke="none"></circle></svg></a><a class="social-icon" href="https://www.tiktok.com/@rebekahspureliving" target="_blank" rel="noopener noreferrer" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.2 4v10.2a4.2 4.2 0 1 1-3.6-4.16"></path><path d="M14.2 4c.75 2.5 2.3 3.9 4.8 4.2"></path></svg></a></div></div></div>
		<details class="footer-group" open><summary>Explore</summary><div class="footer-links"><a href="<?php echo esc_url( home_url( '/in-store-products/' ) ); ?>">In-Store Products</a><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>">Classes &amp; Events</a><a href="<?php echo esc_url( home_url( '/blog/' ) ); ?>">Wellness Source Blog</a><a href="<?php echo esc_url( home_url( '/practitioners/' ) ); ?>">Practitioners</a></div></details>
		<details class="footer-group" open><summary>Locations</summary><div class="footer-links"><a href="<?php echo esc_url( home_url( '/locations/' ) ); ?>">All Locations</a><a href="<?php echo esc_url( home_url( '/locations/lapeer/' ) ); ?>">Lapeer</a><a href="<?php echo esc_url( home_url( '/locations/grand-blanc/' ) ); ?>">Grand Blanc</a><a href="<?php echo esc_url( home_url( '/locations/clarkston/' ) ); ?>">Clarkston</a><a href="<?php echo esc_url( home_url( '/locations/lake-orion/' ) ); ?>">Lake Orion</a></div></details>
		<details class="footer-group" open><summary>About</summary><div class="footer-links"><a href="<?php echo esc_url( home_url( '/our-story/' ) ); ?>">Our Story</a><a href="<?php echo esc_url( home_url( '/our-team/' ) ); ?>">Our Team</a><a href="<?php echo esc_url( home_url( '/contact-us/' ) ); ?>">Contact Us</a></div></details>
		<details class="footer-group" open><summary>Policies</summary><div class="footer-links"><a href="<?php echo esc_url( home_url( '/privacy-policy/' ) ); ?>">Privacy Policy</a><a href="<?php echo esc_url( home_url( '/refund_returns/' ) ); ?>">Refund &amp; Returns</a><a href="<?php echo esc_url( home_url( '/terms-conditions/' ) ); ?>">Terms &amp; Conditions</a><a href="<?php echo esc_url( home_url( '/disclaimer/' ) ); ?>">Disclaimer</a></div></details>
	</div>
	<div class="footer-bottom"><p>&copy; <?php echo esc_html( gmdate( 'Y' ) ); ?> Rebekah's Health &amp; Nutrition &middot; Website Design by <a href="https://bluenovamarketing.com/">Blue Nova Marketing</a></p><nav aria-label="Footer utility navigation"><a href="<?php echo esc_url( home_url( '/sitemap_index.xml' ) ); ?>">Sitemap</a></nav></div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
