<?php
/** Generated from approved mockup: clarkston-location-mockup-v3.1.17.html. */
?>
<main>
<div class="hero"><div class="w hero-grid"><div class="hero-copy"><span class="eye">Clarkston's neighborhood wellness source · Since 2019</span><h1>More clarity for your wellness journey in <em>Clarkston.</em></h1><p>Explore trusted supplements, natural body care, specialty foods, Michigan-made goods and practical guidance from a team that makes questions welcome.</p><div class="actions"><a class="btn gold" href="https://www.google.com/maps/dir/?api=1&destination=7093+Dixie+Highway+Suite+B%2C+Clarkston%2C+MI+48346">Get Directions</a><a class="btn line" href="tel:+12488432011">Call (248) 843-2011</a></div></div><div class="hero-media"><img src="https://rebekahspureliving.com/wp-content/uploads/2026/04/cLARKSTON-STORE3.jpg" alt="Wide view of the shelves and product displays inside Rebekah's Clarkston store"><div class="stamp">Serving Clarkston since<strong>2019</strong></div></div></div></div>
<aside class="quick w"><a href="#visit"><small>Visit us</small><strong>7093 Dixie Hwy, Suite B · Clarkston</strong></a><a href="tel:+12488432011"><small>Call</small><strong>(248) 843-2011</strong></a><div><small>Mon–Sat</small><strong>9am–7pm</strong></div><div><small>Sunday</small><strong>10am–5pm</strong></div></aside>
<section><div class="w split"><img class="portrait" src="<?php echo esc_url( rhn_theme_asset( 'output/clarkston-location/clarkston-team-client.jpg' ) ); ?>" alt="Three Clarkston team members smiling together inside Rebekah's Health and Nutrition"><div class="copy"><span class="eye">Wellness help close to home</span><h2>A Clarkston health store where conversation comes first.</h2><p class="lead">Since opening in 2019, Rebekah's Clarkston has grown into a welcoming stop for neighbors who want good products and a clearer way to compare them.</p><p>Bring a shopping list or simply a question. The team can help you read labels, compare forms and understand everyday options without pressure or one-size-fits-all promises.</p><p class="note">Conveniently located on Dixie Highway and welcoming neighbors from Clarkston, Waterford, Independence Township, Davisburg and nearby communities.</p></div></div></section>
<section class="explore" id="explore"><div class="w"><div class="section-head"><span class="eye">Explore the Clarkston store</span><h2>Useful everyday essentials—and something new to discover.</h2><p>Inventory changes, so call the Clarkston team when you need a specific brand, formula or local product.</p></div><div class="cards">
<article class="card"><b>01</b><h3>Vitamins & supplements</h3><p>Vitamins, minerals, probiotics and specialty formulas for a range of everyday needs.</p></article><article class="card"><b>02</b><h3>Herbs & homeopathy</h3><p>Herbal options, homeopathic products and Rebekah's 200-plus private-label formulas.</p></article><article class="card"><b>03</b><h3>Clean body care</h3><p>Ingredient-conscious bath, body, skincare, cosmetics and personal-care finds.</p></article><article class="card"><b>04</b><h3>Natural foods</h3><p>Organic snacks, teas, protein options, specialty-diet products and pantry staples.</p></article><article class="card"><b>05</b><h3>Oils, honey & gifts</h3><p>Essential oils, diffusers, local honey, jewelry and thoughtful wellness gifts.</p></article><article class="card"><b>06</b><h3>Michigan-made</h3><p>Local makers, rotating vendors and seasonal discoveries rooted close to home.</p></article></div></div></section>
<section class="guide"><div class="w split"><img src="https://rebekahspureliving.com/wp-content/uploads/2024/06/Clarkston-Store.jpg" alt="Product aisles and displays inside the Rebekah's Clarkston store"><div class="copy"><span class="eye">Personal guidance, practical next steps</span><h2>You can ask before you decide.</h2><p class="lead">Our role is to help you understand and compare products—not diagnose conditions or replace advice from a qualified medical professional.</p><div class="facts"><div><strong>Read the label</strong><span>Make ingredients easier to understand.</span></div><div><strong>Compare formats</strong><span>Look at form, serving and value.</span></div><div><strong>Find local goods</strong><span>Discover Michigan makers.</span></div><div><strong>Keep learning</strong><span>Meet educators at store events.</span></div></div></div></div></section>
<section class="events" id="events" data-event-location="clarkston"><div class="w"><div class="section-head"><span class="eye">Happening in Clarkston</span><h2>A store that makes room for community.</h2><p>Clarkston has hosted health and wellness fairs, visiting practitioners, product demonstrations and local vendors. Check the official calendar for current dates and details.</p></div><div class="event-grid">
<article class="event"><div class="event-photo"><img src="https://rebekahspureliving.com/wp-content/uploads/2024/07/Clarkston-Ribbon-Cutting-1024x576-1.jpg" alt="Rebekah's Clarkston team and community celebrating the store's ribbon cutting"></div><div class="event-copy"><small>Community tradition</small><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><h3>Health & Wellness Fairs</h3></a><p>Local practitioners, education, samples and face-to-face connection.</p></div></article>
<article class="event"><div class="event-photo"><img src="https://rebekahspureliving.com/wp-content/uploads/2026/04/cLARKSTON-STORE3.jpg" alt="Current interior of Rebekah's Clarkston store prepared for customers and events"></div><div class="event-copy"><small>Upcoming calendar</small><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><h3>Classes & Demonstrations</h3></a><p>Explore the latest schedule before planning your visit.</p></div></article>
<article class="event"><div class="event-photo"><img src="https://rebekahspureliving.com/wp-content/uploads/2026/04/CLARKSTON-STORE.jpg" alt="Exterior entrance of Rebekah's Health and Nutrition on Dixie Highway in Clarkston"></div><div class="event-copy"><small>Local connection</small><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><h3>Practitioners & Makers</h3></a><p>Meet people sharing practical knowledge and locally made goods.</p></div></article>
</div></div></section>
<section><div class="w split"><div class="copy"><span class="eye">Rooted along Dixie Highway</span><h2>Clarkston brings wellness and community together.</h2><p class="lead">The store serves the greater Clarkston area as a friendly place to shop, slow down and ask questions—whether you are new to natural products or already know the aisles well.</p></div><div class="review"><blockquote>“Great selection and very knowledgeable staff. Rebekah's brings health and wellness to Clarkston.”</blockquote><cite>Third-party review excerpt shown as a design placeholder. Verify the original source and obtain approval before publishing.</cite></div></div></section>
<section class="visit" id="visit"><div class="w split"><div class="copy"><span class="eye">Plan your visit</span><h2>Come see us on Dixie Highway.</h2><p>The store is in Suite B. Call ahead for product availability, holiday hours or event details.</p><div class="details"><div><small>Address</small><strong>7093 Dixie Highway, Suite B<br>Clarkston, MI 48346</strong></div><div><small>Phone</small><strong>(248) 843-2011</strong></div><div><small>Mon–Sat</small><strong>9am–7pm</strong></div><div><small>Sunday</small><strong>10am–5pm</strong></div></div><p class="holiday-hours">Closed on all major holidays.</p><div class="actions"><a class="btn gold" href="https://www.google.com/maps/dir/?api=1&destination=7093+Dixie+Highway+Suite+B%2C+Clarkston%2C+MI+48346">Get Directions</a><a class="btn line" href="tel:+12488432011">Call Clarkston</a></div></div><iframe title="Map showing Rebekah's Clarkston location" loading="lazy" src="https://www.google.com/maps?q=7093+Dixie+Highway+Suite+B,+Clarkston,+MI+48346&output=embed"></iframe></div></section>
<section class="signup"><div class="w split"><div class="copy"><span class="eye">Stay connected with Clarkston</span><h2>Store news, events and updates.</h2><p>Choose Clarkston as your preferred store so locally relevant messages can reach you.</p></div><div class="rhn-location-newsletter" data-default-store="clarkston"><div class="form-title">Join the Rebekah's community</div><?php echo do_shortcode( '[forminator_form id="313"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><small>By signing up, you agree to receive occasional email updates from Rebekah's Health & Nutrition. You may unsubscribe at any time.</small></div></div></section>
</main>
