<?php
/** Generated from approved mockup: lake-orion-location-mockup-v3.1.12.html. */
?>
<main>
<div class="hero"><div class="w hero-grid"><div class="hero-copy"><span class="eye">Lake Orion's neighborhood wellness source · Since 2020</span><h1>Thoughtful wellness support, right here in <em>Lake Orion.</em></h1><p>Explore trusted supplements, natural body care, specialty foods, Michigan-made goods and practical guidance from a team that welcomes questions.</p><div class="actions"><a class="btn gold" href="https://www.google.com/maps/dir/?api=1&destination=1095+S+Lapeer+Road%2C+Lake+Orion%2C+MI+48360">Get Directions</a><a class="btn line" href="tel:+12489298990">Call (248) 929-8990</a></div></div><div class="hero-media"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-store-photo-2.jpg' ) ); ?>" alt="Wide view of the bright aisles and product displays inside Rebekah's Lake Orion store"><div class="stamp">In Lake Orion since<strong>2020</strong></div></div></div></div>
<aside class="quick w"><a href="#visit"><small>Visit us</small><strong>1095 S Lapeer Rd · Lake Orion</strong></a><a href="tel:+12489298990"><small>Call</small><strong>(248) 929-8990</strong></a><div><small>Mon–Fri</small><strong>9am–7pm</strong></div><div><small>Sat–Sun</small><strong>10am–5pm</strong></div></aside>
<section><div class="w split"><img class="portrait" src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-team.jpg' ) ); ?>" alt="Two Lake Orion team members beside an educational product information display"><div class="copy"><span class="eye">Wellness help close to home</span><h2>A Lake Orion health store where questions are welcome.</h2><p class="lead">Opened in 2020, Rebekah's Lake Orion gives local families a friendly place to explore natural products and make more informed choices.</p><p>Bring a shopping list, a label you want to compare or simply a question. The team can help you look at ingredients, formats and everyday options without pressure or one-size-fits-all promises.</p><p class="note">Find us near the corner of M-24 and Clarkston Road, next to Planet Fitness, serving Lake Orion, Orion Township, Oxford, Auburn Hills and nearby communities.</p></div></div></section>
<section class="explore" id="explore"><div class="w"><div class="section-head"><span class="eye">Explore the Lake Orion store</span><h2>Everyday essentials, local finds and room to discover.</h2><p>Inventory changes, so call the Lake Orion team when you need a specific brand, formula or local product.</p></div><div class="cards">
<article class="card"><b>01</b><h3>Vitamins & supplements</h3><p>Vitamins, minerals, probiotics and specialty formulas for a range of everyday needs.</p></article><article class="card"><b>02</b><h3>Herbs & homeopathy</h3><p>Herbal options, homeopathic products and Rebekah's 200-plus private-label formulas.</p></article><article class="card"><b>03</b><h3>Clean body care</h3><p>Ingredient-conscious bath, body, skincare, cosmetics and personal-care finds.</p></article><article class="card"><b>04</b><h3>Natural foods</h3><p>Organic snacks, teas, protein options, specialty-diet products and pantry staples.</p></article><article class="card"><b>05</b><h3>Oils, honey & gifts</h3><p>Essential oils, diffusers, local honey, jewelry and thoughtful wellness gifts.</p></article><article class="card"><b>06</b><h3>Michigan-made</h3><p>Local makers, rotating vendors and seasonal discoveries rooted close to home.</p></article></div></div></section>
<section class="guide"><div class="w split"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-store-photo.jpg' ) ); ?>" alt="Supplement displays and an in-store information board at Rebekah's Lake Orion location"><div class="copy"><span class="eye">Personal guidance, practical next steps</span><h2>You can ask before you decide.</h2><p class="lead">Our role is to help you understand and compare products—not diagnose conditions or replace advice from a qualified medical professional.</p><div class="facts"><div><strong>Read the label</strong><span>Make ingredients easier to understand.</span></div><div><strong>Compare formats</strong><span>Look at form, serving and value.</span></div><div><strong>Find local goods</strong><span>Discover Michigan makers.</span></div><div><strong>Keep learning</strong><span>Meet educators and makers at local events.</span></div></div></div></div></section>
<section class="events" id="events" data-event-location="lake-orion"><div class="w"><div class="section-head"><span class="eye">Happening in Lake Orion</span><h2>Local learning and real community connection.</h2><p>The Lake Orion store has welcomed educational workshops, wellness fairs and seasonal local-goods gatherings. Check the official calendar for current dates and details.</p></div><div class="event-grid">
<article class="event"><div class="event-photo"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-chamber-bagels-brew.jpg' ) ); ?>" alt="Lake Orion Chamber Bagels and Brew gathering hosted inside Rebekah's store"></div><div class="event-copy"><small>Community tradition</small><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><h3>Health & Wellness Fairs</h3></a><p>Meet local educators and practitioners in a welcoming store setting.</p></div></article>
<article class="event"><div class="event-photo"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-team-2.jpg' ) ); ?>" alt="A smiling Lake Orion team member sharing a featured local product"></div><div class="event-copy"><small>Upcoming calendar</small><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><h3>Classes & Workshops</h3></a><p>Explore the latest Lake Orion schedule before planning your visit.</p></div></article>
<article class="event"><div class="event-photo"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-store.jpg' ) ); ?>" alt="Local goods tables and product shelves arranged inside Rebekah's Lake Orion store"></div><div class="event-copy"><small>Seasonal connection</small><a href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><h3>Local Goods & Makers</h3></a><p>Discover seasonal gatherings designed around local food, makers and conversation.</p></div></article>
</div></div></section>
<section><div class="w split"><div class="copy"><span class="eye">Easy to reach from M-24</span><h2>Wellness support for the greater Orion community.</h2><p class="lead">The store is a convenient stop for neighbors from Lake Orion, Orion Township, Oxford and Auburn Hills—whether you are new to natural products or already know exactly what you need.</p></div><div class="review"><blockquote>“Great location right off of 24. Everyone is always so friendly, helpful and willing to take the time to answer questions.”</blockquote><cite>Rebekah's customer</cite></div></div></section>
<section class="visit" id="visit"><div class="w split"><div class="copy"><span class="eye">Plan your visit</span><h2>Come see us on South Lapeer Road.</h2><p>We are near M-24 and Clarkston Road, next to Planet Fitness. Call ahead for product availability, holiday hours or event details.</p><div class="details"><div><small>Address</small><strong>1095 S Lapeer Road<br>Lake Orion, MI 48360</strong></div><div><small>Phone</small><strong>(248) 929-8990</strong></div><div><small>Mon–Fri</small><strong>9am–7pm</strong></div><div><small>Sat–Sun</small><strong>10am–5pm</strong></div></div><p class="holiday-hours">Closed on all major holidays.</p><div class="actions"><a class="btn gold" href="https://www.google.com/maps/dir/?api=1&destination=1095+S+Lapeer+Road%2C+Lake+Orion%2C+MI+48360">Get Directions</a><a class="btn line" href="tel:+12489298990">Call Lake Orion</a></div></div><iframe title="Map showing Rebekah's Lake Orion location" loading="lazy" src="https://www.google.com/maps?q=1095+S+Lapeer+Road,+Lake+Orion,+MI+48360&output=embed"></iframe></div></section>
<section class="signup"><div class="w split"><div class="copy"><span class="eye">Stay connected with Lake Orion</span><h2>Store news, events and updates.</h2><p>Choose Lake Orion as your preferred store so locally relevant messages can reach you.</p></div><div class="rhn-location-newsletter" data-default-store="lake-orion"><div class="form-title">Join the Rebekah's community</div><?php echo do_shortcode( '[forminator_form id="313"]' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><small>By signing up, you agree to receive occasional email updates from Rebekah's Health & Nutrition. You may unsubscribe at any time.</small></div></div></section>
</main>
