<?php
/** Generated from approved mockup: lapeer-location-mockup-v3.1.9.html. */
?>
<main>
<div class="hero"><div class="w hero-grid"><div class="hero-copy"><span class="eye">The original location · Since 2010</span><h1>Your neighborhood wellness source in <em>Lapeer.</em></h1><p>Trusted supplements, natural body care, specialty foods, Michigan-made goods and practical guidance from a team that takes time to listen.</p><div class="actions"><a class="btn gold" href="https://www.google.com/maps/dir/?api=1&destination=588+S+Main+St%2C+Lapeer%2C+MI+48446">Get Directions</a><a class="btn line" href="tel:+18106608585">Call (810) 660-8585</a></div></div><div class="hero-media"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lapeer-location/lapeer-team-2.jpg' ) ); ?>" alt="The Rebekah's Lapeer team inside the store"><div class="stamp">Serving Lapeer since<strong>2010</strong></div></div></div></div>
<aside class="quick w"><a href="#visit"><small>Visit us</small><strong>588 S Main St · Lapeer, MI</strong></a><a href="tel:+18106608585"><small>Call</small><strong>(810) 660-8585</strong></a><div><small>Mon–Sat</small><strong>9am–7pm</strong></div><div><small>Sunday</small><strong>10am–5pm</strong></div></aside>
<section><div class="w split"><img class="portrait" src="<?php echo esc_url( rhn_theme_asset( 'output/lapeer-location/lapeer-team-1.jpg' ) ); ?>" alt="Members of the Rebekah's Lapeer team inside the store"><div class="copy"><span class="eye">Where the story began</span><h2>A local health store built around the conversation.</h2><p class="lead">Lapeer was Rebekah's first store—and it still carries the same promise: make natural wellness easier to understand.</p><p>Come with a specific item in mind or ask the team to help compare formats, labels and everyday options.</p><p class="note">Independent, community-rooted and serving Lapeer-area families since 2010.</p></div></div></section>
<section class="explore" id="explore"><div class="w"><div class="section-head"><span class="eye">Explore the Lapeer store</span><h2>Everyday essentials—and plenty to discover.</h2><p>Selection changes, so call ahead when you need a specific item.</p></div><div class="cards">
<article class="card"><b>01</b><h3>Vitamins & supplements</h3><p>Vitamins, minerals, probiotics and specialty formulas.</p></article><article class="card"><b>02</b><h3>Herbs & homeopathy</h3><p>Herbal options and 200+ Rebekah's private-label formulas.</p></article><article class="card"><b>03</b><h3>Clean body care</h3><p>Bath, body, skincare and cosmetics.</p></article><article class="card"><b>04</b><h3>Natural foods</h3><p>Organic snacks, teas, proteins and pantry finds.</p></article><article class="card"><b>05</b><h3>Oils & gifts</h3><p>Essential oils, diffusers, jewelry and wellness gifts.</p></article><article class="card"><b>06</b><h3>Michigan-made</h3><p>Local makers, rotating pop-ups and seasonal favorites.</p></article></div></div></section>
<section class="guide"><div class="w split"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lapeer-location/lapeer-victoria-education.jpg' ) ); ?>" alt="Victoria sharing educational materials inside the Lapeer store"><div class="copy"><span class="eye">Guidance that feels personal</span><h2>You do not have to know where to start.</h2><p class="lead">We help compare choices and clarify next steps—not diagnose or replace medical care.</p><div class="facts"><div><strong>Ask questions</strong><span>Talk through labels.</span></div><div><strong>Compare options</strong><span>Review form and price.</span></div><div><strong>Discover local</strong><span>Meet Michigan makers.</span></div><div><strong>Keep learning</strong><span>Join store events.</span></div></div></div></div></section>
<section class="events" id="events" data-event-location="lapeer"><div class="w"><div class="section-head"><span class="eye">Happening in Lapeer</span><h2>More than a place to shop.</h2><p>Dates can change; check the official listing before visiting.</p><p class="event-filter-note">This section automatically displays upcoming events assigned to the Lapeer location.</p></div><div class="event-grid"><a class="event" href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><img src="https://rebekahspureliving.com/wp-content/uploads/2026/04/IMG_0508.jpg" alt="Fresh microgreens"><div><small>Tuesdays · 10am–3pm</small><h3>Local Microgreens</h3><p>A recurring Mighty Greens pop-up.</p></div></a><a class="event" href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><img src="https://rebekahspureliving.com/wp-content/uploads/2025/05/Eva-new-website-photo.jpg" alt="Artisan sourdough"><div><small>Wednesdays · 10am–1pm</small><h3>Eva's Sourdough</h3><p>A weekly artisan bread pop-up.</p></div></a><a class="event" href="<?php echo esc_url( home_url( '/events/' ) ); ?>"><img src="https://rebekahspureliving.com/wp-content/uploads/2026/06/Lapeer-pop-up-massage.jpg" alt="Chair massage event"><div><small>July 24 · 10am–3pm</small><h3>Chair Massage Pop-Up</h3><p>See the event listing for details.</p></div></a></div></div></section>
<section><div class="w split"><div class="copy"><span class="eye">Rooted in Lapeer</span><h2>Local connection is part of the experience.</h2><p class="lead">Welcoming neighbors from Lapeer, Metamora, Imlay City, Davison and surrounding communities.</p></div><div class="review"><blockquote>“Huge store, so many options! Staff is super helpful.”</blockquote><cite>Third-party feedback shown as a design placeholder. Confirm permission and sourcing before launch.</cite></div></div></section>
<section class="visit" id="visit"><div class="w split"><div class="copy"><span class="eye">Plan your visit</span><h2>Come see us on South Main Street.</h2><p>Call ahead for product availability or open directions.</p><div class="details"><div><small>Address</small><strong>588 S Main St<br>Lapeer, MI 48446</strong></div><div><small>Phone</small><strong>(810) 660-8585</strong></div><div><small>Mon–Sat</small><strong>9am–7pm</strong></div><div><small>Sunday</small><strong>10am–5pm</strong></div></div><p class="holiday-hours">Closed on all major holidays.</p><div class="actions"><a class="btn gold" href="https://www.google.com/maps/dir/?api=1&destination=588+S+Main+St%2C+Lapeer%2C+MI+48446">Get Directions</a><a class="btn line" href="tel:+18106608585">Call Lapeer</a></div></div><iframe title="Map showing Rebekah's Lapeer" loading="lazy" src="https://www.google.com/maps?q=588+S+Main+St,+Lapeer,+MI+48446&output=embed"></iframe></div></section>
<section class="signup"><div class="w split"><div class="copy"><span class="eye">Stay connected with Lapeer</span><h2>Store news, events and updates.</h2><p>Choose Lapeer as your preferred store for locally relevant messages.</p></div><form><div class="form-title wide">Join the Rebekah's community</div><input type="text" placeholder="Your name" aria-label="Your name"><input type="email" placeholder="Your email address" aria-label="Your email address" required><select class="wide" aria-label="Preferred store" required><option value="">Choose your preferred store</option><option selected>Lapeer</option><option>Grand Blanc</option><option>Clarkston</option><option>Lake Orion</option></select><button class="btn wide" type="button">Sign Up for Updates</button><small class="wide">By signing up, you agree to receive occasional email updates from Rebekah's Health & Nutrition. You may unsubscribe at any time.</small></form></div></section>
</main>
