<?php
/** Generated from approved mockup: locations-mockup-v2.9.0.html. */
?>
<main id="main">
    <section class="hero">
      <div class="wrap hero-grid">
        <div class="hero-copy"><span class="eyebrow">Four Michigan communities · one caring team</span><h1>Find your neighborhood <em>wellness source.</em></h1><p>Visit Rebekah’s in Lapeer, Grand Blanc, Clarkston or Lake Orion for trusted supplements, natural products and thoughtful guidance from people who take time to listen.</p><div class="hero-actions"><a class="button primary" href="#stores">Compare all four stores</a><a class="button outline" href="#what-to-expect">What to expect</a></div></div>
        <div class="store-photo-panel" aria-label="Explore Rebekah's four Michigan stores">
          <a class="store-photo" href="#lapeer"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lapeer-location/lapeer-team-2.jpg' ) ); ?>" alt="The Rebekah's Lapeer team inside the store"><span><strong>Lapeer</strong><small>Meet the store</small></span></a>
          <a class="store-photo" href="#grand-blanc"><img src="<?php echo esc_url( rhn_theme_asset( 'output/grand-blanc-location/grand-blanc-team-drive.jpg' ) ); ?>" alt="Grand Blanc team members inside Rebekah's Health and Nutrition"><span><strong>Grand Blanc</strong><small>Meet the store</small></span></a>
          <a class="store-photo" href="#clarkston"><img src="https://rebekahspureliving.com/wp-content/uploads/2026/04/cLARKSTON-STORE3.jpg" alt="Product displays inside Rebekah's Clarkston store"><span><strong>Clarkston</strong><small>See the store</small></span></a>
          <a class="store-photo" href="#lake-orion"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-store-photo-2.jpg' ) ); ?>" alt="Bright aisles and product displays inside Rebekah's Lake Orion store"><span><strong>Lake Orion</strong><small>See the store</small></span></a>
        </div>
      </div>
    </section>
    <section class="finder" id="stores">
      <div class="wrap">
        <div class="finder-head"><div><span class="eyebrow">Choose your store</span><h2>Four places to feel right at home.</h2></div><p>Compare addresses, phone numbers and regular hours at a glance. Select a store for directions or visit its page for local events, photos and updates.</p></div>
        <div class="location-grid">
          <article class="location-card" id="lapeer"><div class="card-marker"><b>01</b><span>Lapeer County</span></div><div class="card-body"><h3>Lapeer</h3><p class="address">588 S Main St<br>Lapeer, MI 48446</p><div class="details"><div><strong>Regular hours</strong>Mon–Sat: 9am–7pm<br>Sun: 10am–5pm</div><div><strong>Call the store</strong><a class="phone" href="tel:18106608585">(810) 660-8585</a></div></div><div class="card-actions"><a class="button dark" href="https://www.google.com/maps/dir/?api=1&destination=588+S+Main+St+Lapeer+MI+48446">Get directions</a><a class="text-link" href="/locations/lapeer/">Explore Lapeer →</a></div></div></article>
          <article class="location-card" id="grand-blanc"><div class="card-marker"><b>02</b><span>Genesee County</span></div><div class="card-body"><h3>Grand Blanc</h3><p class="address">252 Perry Road, Suite 4<br>Grand Blanc, MI 48439</p><div class="details"><div><strong>Regular hours</strong>Mon–Sat: 9am–7pm<br>Sun: 10am–5pm</div><div><strong>Call the store</strong><a class="phone" href="tel:18108664642">(810) 866-4642</a></div></div><div class="card-actions"><a class="button dark" href="https://www.google.com/maps/dir/?api=1&destination=252+Perry+Road+Grand+Blanc+MI+48439">Get directions</a><a class="text-link" href="/locations/grand-blanc/">Explore Grand Blanc →</a></div></div></article>
          <article class="location-card" id="clarkston"><div class="card-marker"><b>03</b><span>Oakland County</span></div><div class="card-body"><h3>Clarkston</h3><p class="address">7093 Dixie Highway, Suite B<br>Clarkston, MI 48346</p><div class="details"><div><strong>Regular hours</strong>Mon–Sat: 9am–7pm<br>Sun: 10am–5pm</div><div><strong>Call the store</strong><a class="phone" href="tel:12488432011">(248) 843-2011</a></div></div><div class="card-actions"><a class="button dark" href="https://www.google.com/maps/dir/?api=1&destination=7093+Dixie+Highway+Clarkston+MI+48346">Get directions</a><a class="text-link" href="/locations/clarkston/">Explore Clarkston →</a></div></div></article>
          <article class="location-card" id="lake-orion"><div class="card-marker"><b>04</b><span>Oakland County</span></div><div class="card-body"><h3>Lake Orion</h3><p class="address">1095 S Lapeer Road<br>Lake Orion, MI 48360</p><div class="details"><div><strong>Regular hours</strong>Mon–Fri: 9am–7pm<br>Sat–Sun: 10am–5pm</div><div><strong>Call the store</strong><a class="phone" href="tel:12489298990">(248) 929-8990</a></div></div><div class="card-actions"><a class="button dark" href="https://www.google.com/maps/dir/?api=1&destination=1095+S+Lapeer+Road+Lake+Orion+MI+48360">Get directions</a><a class="text-link" href="/locations/lake-orion/">Explore Lake Orion →</a></div></div></article>
        </div>
      </div>
    </section>
    <section class="expect" id="what-to-expect">
      <div class="wrap"><div class="expect-head"><span class="eyebrow">The Rebekah’s difference</span><h2>More than shelves. A place to ask questions.</h2><p>Whether you know exactly what you need or are simply looking for a place to begin, our teams are here to help you compare options and shop with greater confidence.</p></div><div class="expect-grid"><article class="expect-card"><span>01</span><h3>Knowledgeable, personal guidance</h3><p>Talk through products and everyday wellness goals with a caring team—without pressure or one-size-fits-all promises.</p></article><article class="expect-card"><span>02</span><h3>A thoughtfully chosen selection</h3><p>Explore vitamins, herbs, homeopathic products, clean body care, specialty foods, local goods and Rebekah’s private label formulas.</p></article><article class="expect-card"><span>03</span><h3>Learning close to home</h3><p>Discover classes, visiting educators, community events and practical resources designed to make wellness feel more understandable.</p></article></div></div>
    </section>
    <section class="visit-cta"><div class="visit-copy"><span class="eyebrow">Come as you are</span><h2>Your next step can start with a conversation.</h2><p>Choose the store nearest you, stop in and meet the people behind Rebekah’s community-rooted approach to wellness.</p><div class="visit-actions"><a class="button primary" href="#stores">Choose your store</a><a class="button outline" href="/events/">Explore classes & events</a></div></div><div class="visit-image" role="img" aria-label="Rebekah's Health & Nutrition community at a Clarkston ribbon cutting"></div></section>
  </main>
