<?php
/** Generated from approved mockup: our-team-mockup-v1.0.0.html. */
?>
<main id="main">
    <section class="team-hero">
      <div class="team-wrap team-hero-grid">
        <div class="team-hero-copy">
          <span class="team-eyebrow">Our people</span>
          <h1>Meet the team <em>behind the care.</em></h1>
          <p>Across four Michigan stores, our team brings curiosity, continuing education and a genuine desire to help. Meet the people who make every visit feel personal.</p>
          <div class="hero-actions"><a class="pill honey" href="<?php echo esc_url( home_url( '/locations/' ) ); ?>">Find your store</a></div>
        </div>
        <div class="hero-collage" aria-label="Rebekah's teams across four Michigan stores">
          <figure class="hero-photo one"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lapeer-location/lapeer-team-1.jpg' ) ); ?>" alt="Team members together inside Rebekah's Lapeer store"><figcaption>Lapeer</figcaption></figure>
          <figure class="hero-photo two"><img src="<?php echo esc_url( rhn_theme_asset( 'output/grand-blanc-location/grand-blanc-team-drive.jpg' ) ); ?>" alt="Team members together inside Rebekah's Grand Blanc store"><figcaption>Grand Blanc</figcaption></figure>
          <figure class="hero-photo three"><img src="<?php echo esc_url( rhn_theme_asset( 'output/clarkston-location/clarkston-team-client.jpg' ) ); ?>" alt="Team members together inside Rebekah's Clarkston store"><figcaption>Clarkston</figcaption></figure>
          <figure class="hero-photo four"><img src="<?php echo esc_url( rhn_theme_asset( 'output/lake-orion-location/lake-orion-team.jpg' ) ); ?>" alt="Team members together inside Rebekah's Lake Orion store"><figcaption>Lake Orion</figcaption></figure>
          <div class="hero-badge"><strong>10</strong><span>team stories · one shared purpose</span></div>
        </div>
      </div>
    </section>

    <div class="team-proof"><div class="team-wrap proof-panel"><div class="proof-intro"><strong>Guidance starts with listening.</strong><span>Real people. Thoughtful questions. Practical next steps.</span></div><div><strong>4</strong><span>Michigan stores</span></div><div><strong>10</strong><span>team stories</span></div><div><strong>1</strong><span>caring community</span></div></div></div>

    <section class="team-intro" id="meet-the-team">
      <div class="team-wrap intro-grid"><div><span class="team-eyebrow">People before products</span><h2>Knowledgeable by choice. Caring by nature.</h2></div><div class="intro-copy"><p>Some team members came to Rebekah's with years of health-food experience. Others discovered a calling through the customers, classes and daily learning inside our stores. Every story is different, but the purpose is shared.</p><p>We are here to make the wellness aisle feel less overwhelming—by listening first, sharing what we know and helping each visitor make informed choices that fit their own goals and lifestyle.</p></div></div>
    </section>

    <nav class="store-jump team-wrap" aria-label="Jump to a store team"><div class="store-jump-panel"><a href="#lapeer-team"><small>01 · Lapeer</small><b>Meet the Lapeer team</b><span>3 stories →</span></a><a href="#grand-blanc-team"><small>02 · Grand Blanc</small><b>Meet the Grand Blanc team</b><span>4 stories →</span></a><a href="#clarkston-team"><small>03 · Clarkston</small><b>Meet the Clarkston team</b><span>2 stories →</span></a><a href="#lake-orion-team"><small>04 · Lake Orion</small><b>Meet the Lake Orion team</b><span>1 story →</span></a></div></nav>

    <section class="location-team alt" id="lapeer-team">
      <div class="team-wrap"><header class="location-head"><div><span class="team-eyebrow">Lapeer · Our first location</span><h2>Meet your Lapeer team.</h2></div><p>Passionate educators and familiar faces ready to help you explore natural wellness with confidence.</p></header>
        <div class="team-grid">
          <article class="team-card"><div class="team-card-media"><img class="portrait-high" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/angie.jpg' ) ); ?>" alt="Angela Basner, Store Manager at Rebekah's Lapeer"><span class="store-tag">Lapeer</span></div><div class="team-card-content"><h3>Angela Basner</h3><span class="role">Store Manager · Transformational Life Coach</span><p class="card-summary">Angela brings compassion, practical guidance and a whole-person perspective to every customer conversation.</p><details class="bio"><summary>Read Angela's full bio</summary><div class="bio-copy"><p>Angela Basner is the Store Manager at Rebekah's Health & Nutrition in Lapeer and a certified Transformational Life Coach with a passion for natural wellness. She enjoys helping customers explore personalized options through nutrition, supplements and healthy lifestyle choices.</p><p>Angela believes wellness begins within and includes nourishing the mind, body and spirit. She is dedicated to educating, empowering and encouraging others with compassion and practical guidance.</p><p>Outside of work, Angela enjoys hiking, kayaking, exploring nature, reading about holistic health, traveling and spending quality time with her family. She is passionate about lifelong learning and inspiring others to live healthier, more balanced and meaningful lives.</p></div></details></div></article>
          <article class="team-card"><div class="team-card-media"><img class="portrait-top" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/pam.jpg' ) ); ?>" alt="Pamela Stuewer, Wellness Coach at Rebekah's Lapeer"><span class="store-tag">Lapeer</span></div><div class="team-card-content"><h3>Pamela Stuewer</h3><span class="role">Wellness Coach</span><p class="card-summary">For Pam, the best part of the day is helping people become more aware of themselves and their natural wellness options.</p><details class="bio"><summary>Read Pam's full bio</summary><div class="bio-copy"><p>Rebekah's Health & Nutrition has molded me into the person I am today.</p><p>Nine years of co-workers, customers, products, challenges, tears and smiles—it all works together to make us more passionate about our health.</p><p>The best part of my day is helping others become more aware of themselves and the natural alternatives available.</p></div></details></div></article>
          <article class="team-card"><div class="team-card-media"><img class="portrait-center" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/ashlyn.jpg' ) ); ?>" alt="Ashlyn, Wellness Coach at Rebekah's Lapeer"><span class="store-tag">Lapeer</span></div><div class="team-card-content"><h3>Ashlyn</h3><span class="role">Wellness Coach</span><p class="card-summary">Ashlyn's time at Rebekah's has grown an interest in holistic health into a lifelong passion for learning.</p><details class="bio"><summary>Read Ashlyn's full bio</summary><div class="bio-copy"><p>Hi, I'm Ashlyn! Throughout my employment at Rebekah's Health & Nutrition, I've developed more than an interest in holistic health—I've found a lifelong passion.</p><p>In the future, I plan to pursue higher education with the goal of becoming a compounding pharmacist specializing in holistic health. Right now, I continue expanding my knowledge of natural wellness while pursuing other passions such as babysitting and coaching youth cheerleading.</p><p>I'm beyond grateful for the team members, customers and community members who have supported me on my path of learning and growth. I look forward to what the future holds and am honored to be part of the Rebekah's team!</p></div></details></div></article>
        </div>
      </div>
    </section>

    <section class="location-team" id="grand-blanc-team">
      <div class="team-wrap"><header class="location-head"><div><span class="team-eyebrow">Grand Blanc · Experience meets curiosity</span><h2>Meet your Grand Blanc team.</h2></div><p>A thoughtful mix of deep industry experience, holistic health education and a love of helping people learn.</p></header>
        <div class="team-grid four">
          <article class="team-card"><div class="team-card-media"><img class="portrait-high" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/todd.jpg' ) ); ?>" alt="Todd Cochell, Store Manager at Rebekah's Grand Blanc"><span class="store-tag">Grand Blanc</span></div><div class="team-card-content"><h3>Todd Cochell</h3><span class="role">Store Manager</span><p class="card-summary">Todd brings more than 25 years of health-food industry experience and an education-first approach to Grand Blanc.</p><details class="bio"><summary>Read Todd's full bio</summary><div class="bio-copy"><p>Todd Cochell brings more than 25 years of health-food industry experience to his role as Store Manager at Rebekah's Health & Nutrition in Grand Blanc.</p><p>His career began in health food stores, where a desire to help people and a passion for natural wellness grew into a lifelong commitment to learning. Over the years, Todd has continued to expand his knowledge through research, education and the experiences shared by the people he has served.</p><p>From 2016 to 2020, Todd worked with Garden of Life as a Product Specialist and Educator. That experience further strengthened his understanding of supplements, nutrition and the importance of helping customers make informed choices for their individual wellness goals.</p><p>Todd is proud to be part of Rebekah's, a company whose values align closely with his own: education, integrity and genuine care for the community. He looks forward to meeting new customers, sharing what he has learned and helping create a welcoming place where people feel comfortable asking questions.</p></div></details></div></article>
          <article class="team-card"><div class="team-card-media"><img class="portrait-center" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/jackelyn.jpg' ) ); ?>" alt="Jackelyn, Holistic Health Practitioner at Rebekah's Grand Blanc"><span class="store-tag">Grand Blanc</span></div><div class="team-card-content"><h3>Jackelyn</h3><span class="role">Holistic Health Practitioner</span><p class="card-summary">A lifelong love of nourishing food, family wellness and research led Jackelyn naturally to Rebekah's.</p><details class="bio"><summary>Read Jackelyn's full bio</summary><div class="bio-copy"><p>Growing up in a health-conscious family, eating nourishing foods was always part of my life. I was free to experiment with recipes, which began a love of cooking and naturally led to adapting dishes to be more healthful.</p><p>Becoming a mother brought a heightened awareness of raising healthy, thriving children. Being a mother of seven, with four babies born at home, also led me to learn more about prenatal and postnatal wellness.</p><p>Instinctively a researcher, I began diving deeper into alternative health. Seeing positive changes in my family's daily wellness strengthened my desire to help others, and my employment at Rebekah's was a perfect fit.</p><p>The education provided through classes and becoming a certified Holistic Health Practitioner have given me more confidence in supporting customers, friends and family as they explore informed wellness choices.</p><p>In my free time, I love taking nature walks with my family, exploring the plants and herbs along the way and appreciating God's creation. I love the life my husband and I have created and find joy in helping others feel supported in theirs.</p></div></details></div></article>
          <article class="team-card"><div class="team-card-media"><img class="portrait-top" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/debbie.jpg' ) ); ?>" alt="Debbie, Holistic Health Practitioner at Rebekah's Grand Blanc"><span class="store-tag">Grand Blanc</span></div><div class="team-card-content"><h3>Debbie</h3><span class="role">Holistic Health Practitioner · Wellness Coach</span><p class="card-summary">Debbie pairs more than 25 years of personal wellness study with a caring, individualized approach.</p><details class="bio"><summary>Read Debbie's full bio</summary><div class="bio-copy"><p>I am a Holistic Health Practitioner, dietary supplement specialist and wellness coach at Rebekah's Health & Nutrition.</p><p>I began studying and practicing wellness more than 25 years ago because I wanted a better quality of health for myself. That personal journey grew into a lifelong passion for helping others make informed, practical choices that support their own wellness goals.</p><p>My career began as a hairdresser and in-salon educator, where I discovered how much I enjoyed helping people look and feel their best. From there, I continued building on that passion through ongoing education in holistic health, nutrition and supplements.</p><p>Today, I bring that same caring, individualized approach to customer consultations at Rebekah's. I enjoy listening to each person's needs and helping them explore wellness options that fit their lifestyle.</p></div></details></div></article>
          <article class="team-card"><div class="team-card-media"><img class="portrait-center" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/brian.jpg' ) ); ?>" alt="Brian, Holistic Health Practitioner at Rebekah's Grand Blanc"><span class="store-tag">Grand Blanc</span></div><div class="team-card-content"><h3>Brian</h3><span class="role">Holistic Health Practitioner</span><p class="card-summary">Brian brings creativity, curiosity and a warm, thoughtful presence to each customer conversation.</p><details class="bio"><summary>Read Brian's full bio</summary><div class="bio-copy"><p>Brian has been a valued member of the Rebekah's Health & Nutrition Grand Blanc team since 2024. He brings a warm, creative and thoughtful approach to helping customers explore products and practices that support their individual wellness routines.</p><p>In 2025, Brian earned his certification as a Holistic Health Practitioner. He has also completed hundreds of hours of education in nutrition, supplements and herbs, allowing him to share knowledgeable, practical product information with customers.</p><p>With interests in wellness coaching, essential oils, homeopathy, crystals, mindfulness and self-care, Brian enjoys creating a welcoming space where people feel comfortable asking questions and learning about new options. He is also a musician, creative artist and entrepreneur, bringing curiosity and heart into everything he does.</p><p>Brian believes wellness looks different for every person. His goal is to listen, share educational information and help customers feel supported as they make choices that align with their own goals and lifestyle.</p></div></details></div></article>
        </div>
      </div>
    </section>

    <section class="location-team pine" id="clarkston-team">
      <div class="team-wrap"><header class="location-head"><div><span class="team-eyebrow">Clarkston · Growing together</span><h2>Meet your Clarkston team.</h2></div><p>Relationships, continuing education and fresh ideas come together in a team invested in the people it serves.</p></header>
        <div class="team-grid two">
          <article class="team-card"><div class="team-card-media"><img class="portrait-center" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/margaret.jpg' ) ); ?>" alt="Margaret, Store Manager at Rebekah's Clarkston"><span class="store-tag">Clarkston</span></div><div class="team-card-content"><h3>Margaret</h3><span class="role">Store Manager · Holistic Nutritionist</span><p class="card-summary">Margaret loves building customer relationships and is continuing her education in holistic nutrition.</p><details class="bio"><summary>Read Margaret's full bio</summary><div class="bio-copy"><p>Hi, I'm Margaret! I've been part of the Rebekah's Health & Nutrition family for the past five years and currently manage our Clarkston location. I love building relationships with our customers and helping them pursue their health and wellness goals.</p><p>My passion for natural health has grown through both hands-on experience and education. I recently completed my schooling and am now a Holistic Nutritionist. I'm currently studying to become a Board Certified Holistic Nutritionist (BCHN) so I can continue expanding my knowledge and better serve those in our community.</p><p>Looking ahead, my dream is to build a business of my own while continuing to make a positive impact in the health and wellness field. I'm excited for what the future holds and grateful to be part of a team that shares my passion for helping others live healthier, happier lives.</p></div></details></div></article>
          <article class="team-card"><div class="team-card-media has-native"><img class="portrait-native" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/catie.jpg' ) ); ?>" alt="Catie, Store Purchaser at Rebekah's Clarkston"><span class="store-tag">Clarkston</span></div><div class="team-card-content"><h3>Catie</h3><span class="role">Store Purchaser</span><p class="card-summary">Catie loves discovering new products, following nutrition trends and building a career centered on health and fitness.</p><details class="bio"><summary>Read Catie's full bio</summary><div class="bio-copy"><p>Hi, I'm Catie! I've been part of the Rebekah's Health & Nutrition family for almost three years. I started as a cashier and worked my way into my current role as the store's purchaser. I love discovering new products, staying on top of the latest trends in health and nutrition and helping ensure our stores have the best selection for our customers.</p><p>My passion for health and fitness continues to grow through both hands-on experience and education. I'm currently working toward my NASM Certified Personal Trainer and Nutrition Coach certifications to expand my knowledge and better help others reach their health and wellness goals.</p><p>Looking ahead, I hope to continue growing with Rebekah's while building a career centered around health, fitness and helping people live healthier lives. I'm grateful to be part of a team that's passionate about making a positive impact in our community.</p></div></details></div></article>
        </div>
      </div>
    </section>

    <section class="location-team alt" id="lake-orion-team">
      <div class="team-wrap"><header class="location-head"><div><span class="team-eyebrow">Lake Orion · Mind and body</span><h2>Meet your Lake Orion team.</h2></div><p>Thoughtful product education and a whole-person view of wellness guide every interaction at Lake Orion.</p></header>
        <div class="team-grid solo">
          <article class="team-card"><div class="team-card-media"><img class="portrait-center" src="<?php echo esc_url( rhn_theme_asset( 'output/our-team/assets/mikayla.jpg' ) ); ?>" alt="Mikayla, Manager and Purchaser at Rebekah's Lake Orion"><span class="store-tag">Lake Orion</span></div><div class="team-card-content"><h3>Mikayla</h3><span class="role">Manager · Purchaser</span><p class="card-summary">Mikayla combines ongoing product education with graduate study in clinical mental health counseling and a thoughtful mind-and-body perspective.</p><details class="bio"><summary>Read Mikayla's full bio</summary><div class="bio-copy"><p>We are excited to introduce Mikayla, the Manager and Purchaser of Rebekah's Health & Nutrition in Lake Orion.</p><p>Mikayla has a true passion for health, wellness and helping people feel their best. One of her favorite parts of working at Rebekah's is getting to know our customers and helping them discover products that fit their individual goals, lifestyles and needs.</p><p>Whether you are looking for vitamins, natural wellness products, healthier food options or simply have questions about where to begin, Mikayla is always happy to help.</p><p>She has completed product education and certification programs through companies including Terry Naturally, Panoram, Host Defense and others. Continuing education helps her stay informed about new products, ingredients and wellness education. Her goal is never simply to sell a product—it is to help each person make an informed decision they feel good about.</p><p>Mikayla is also pursuing her master's degree in Clinical Mental Health Counseling at Oakland University. Her education has strengthened her belief that wellness includes caring for both the mind and body, and she brings that thoughtful perspective into the store every day.</p><p>We are grateful to have Mikayla leading our Lake Orion location. Stop in, say hello and let her help you explore your next wellness step with confidence.</p></div></details></div></article>
        </div>
      </div>
    </section>

    <section class="team-note"><div class="team-wrap team-note-inner"><div class="team-note-mark"><strong>10</strong><span>stories worth sharing</span></div><div class="team-note-copy"><span class="team-eyebrow">A team that keeps learning</span><h2>Wellness knowledge is never finished.</h2><p>Our team members study, ask questions, attend product education and learn from the people they serve. We value that curiosity because good guidance begins with humility—and the willingness to keep growing.</p><p>Our role is educational. We help you compare products and understand available options; we do not diagnose, prescribe or replace advice from a qualified healthcare professional.</p></div></div></section>

    <section class="visit-team"><div class="visit-team-copy"><span class="team-eyebrow">Come say hello</span><h2>Meet your team in person.</h2><p>The best way to experience Rebekah's is to walk through the door, ask a question and start a conversation. Find the store nearest you and meet the people ready to help.</p><div class="visit-actions"><a class="pill honey" href="<?php echo esc_url( home_url( '/locations/' ) ); ?>">Find your store</a><a class="pill hero-secondary" href="<?php echo esc_url( home_url( '/events/' ) ); ?>">Explore classes & events</a></div></div><div class="visit-team-media"><img src="<?php echo esc_url( rhn_theme_asset( 'output/clarkston-location/clarkston-team-client.jpg' ) ); ?>" alt="The Rebekah's team welcoming customers at the Clarkston store"></div></section>
    <p class="source-note">Team bios and portraits are based on information shared by participating Rebekah's staff members. For current roles, credentials and availability, please contact the applicable store directly.</p>
  </main>
